# Generated by Django 4.2.7 on 2025-12-07 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ButceKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe Kategorisi",
                "verbose_name_plural": "Bütçe Kategorileri",
                "db_table": "butce_butcekategori",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Butce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                (
                    "donem",
                    models.CharField(
                        choices=[
                            ("aylik", "Aylık"),
                            ("yillik", "Yıllık"),
                            ("ozel", "Özel"),
                        ],
                        max_length=20,
                        verbose_name="Dönem",
                    ),
                ),
                ("baslangic_tarihi", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("bitis_tarihi", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "butce_tutari",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Bütçe Tutarı (₺)"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="butce.butcekategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bütçe",
                "verbose_name_plural": "Bütçeler",
                "db_table": "butce_butce",
                "ordering": ["-baslangic_tarihi"],
            },
        ),
    ]
