# Generated by Django 4.2.7 on 2025-12-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Musteri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                (
                    "unvan",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ünvan"
                    ),
                ),
                (
                    "tc_vkn",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="TC/ Vergi No",
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "sehir",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Şehir"
                    ),
                ),
                (
                    "tip",
                    models.CharField(
                        choices=[("Bireysel", "Bireysel"), ("Kurumsal", "Kurumsal")],
                        default="Bireysel",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "bakiye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Bakiye",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri",
                "verbose_name_plural": "Müşteriler",
                "db_table": "cari_musteri",
                "ordering": ["ad_soyad"],
            },
        ),
    ]
