# Generated by Django 4.2.7 on 2025-12-07 13:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_soyad",
                    models.CharField(
                        max_length=200, verbose_name="Ad Soyad / Firma Adı"
                    ),
                ),
                (
                    "vergi_dairesi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Vergi Numarası",
                    ),
                ),
                (
                    "tc_vkn",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="TCKN / VKN"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "adres",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "sehir",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Şehir"
                    ),
                ),
                (
                    "ilce",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="İlçe"
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("musteri", "Müşteri"),
                            ("tedarikci", "Tedarikçi"),
                            ("her_ikisi", "Her İkisi"),
                        ],
                        default="musteri",
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[("aktif", "Aktif"), ("pasif", "Pasif")],
                        default="aktif",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "risk_limiti",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Risk Limiti (₺)",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari",
                "verbose_name_plural": "Cariler",
                "db_table": "cari_cari",
                "ordering": ["ad_soyad"],
            },
        ),
        migrations.CreateModel(
            name="CariHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hareket_turu",
                    models.CharField(
                        choices=[
                            ("satis_faturasi", "Satış Faturası"),
                            ("alis_faturasi", "Alış Faturası"),
                            ("tahsilat", "Tahsilat (Ödeme Alındı)"),
                            ("odeme", "Ödeme (Para Ödendi)"),
                            ("iade", "İade / İptal"),
                        ],
                        max_length=20,
                        verbose_name="Hareket Türü",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Belge Numarası",
                    ),
                ),
                ("tarih", models.DateTimeField(verbose_name="Tarih")),
                (
                    "odeme_yontemi",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nakit", "Nakit"),
                            ("havale", "Havale"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                            ("senet", "Senet"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Hareketi",
                "verbose_name_plural": "Cari Hareketleri",
                "db_table": "cari_carihareketi",
                "ordering": ["-tarih", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CariNotu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("icerik", models.TextField(verbose_name="İçerik")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cari Notu",
                "verbose_name_plural": "Cari Notları",
                "db_table": "cari_carinotu",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
