# Generated by Django 4.2.7 on 2025-12-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fatura", "0002_remove_fatura_musteri_fatura_cari"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cari", "0002_cari_carihareketi_carinotu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Musteri",
        ),
        migrations.AddField(
            model_name="carinotu",
            name="cari",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notlar",
                to="cari.cari",
                verbose_name="Cari",
            ),
        ),
        migrations.AddField(
            model_name="carinotu",
            name="olusturan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
        migrations.AddField(
            model_name="carihareketi",
            name="cari",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hareketler",
                to="cari.cari",
                verbose_name="Cari",
            ),
        ),
        migrations.AddField(
            model_name="carihareketi",
            name="olusturan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="İşlemi Yapan",
            ),
        ),
    ]
