# Generated by Django 4.2.7 on 2025-12-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cari", "0003_delete_musteri_carinotu_cari_carinotu_olusturan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TediyeMakbuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "makbuz_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Makbuz No"
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("havale", "Havale"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                            ("senet", "Senet"),
                        ],
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "dekont_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dekont No"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tediye_makbuzlari",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tediye Makbuzu",
                "verbose_name_plural": "Tediye Makbuzları",
                "db_table": "cari_tediyemakbuzu",
                "ordering": ["-tarih", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TahsilatMakbuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "makbuz_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Makbuz No"
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                (
                    "odeme_yontemi",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("havale", "Havale"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                            ("senet", "Senet"),
                        ],
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "dekont_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Dekont No"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tahsilat_makbuzlari",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahsilat Makbuzu",
                "verbose_name_plural": "Tahsilat Makbuzları",
                "db_table": "cari_tahsilatmakbuzu",
                "ordering": ["-tarih", "-id"],
            },
        ),
    ]
