# Generated by Django 6.0 on 2025-12-10 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0004_tediyemakbuzu_tahsilatmakbuzu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cari",
            index=models.Index(fields=["durum"], name="cari_durum_idx"),
        ),
        migrations.AddIndex(
            model_name="cari",
            index=models.Index(fields=["kategori"], name="cari_kategori_idx"),
        ),
        migrations.AddIndex(
            model_name="cari",
            index=models.Index(fields=["ad_soyad"], name="cari_ad_soyad_idx"),
        ),
        migrations.AddIndex(
            model_name="cari",
            index=models.Index(fields=["vergi_no"], name="cari_vergi_no_idx"),
        ),
        migrations.AddIndex(
            model_name="carihareketi",
            index=models.Index(fields=["tarih"], name="carihareketi_tarih_idx"),
        ),
        migrations.AddIndex(
            model_name="carihareketi",
            index=models.Index(
                fields=["hareket_turu"], name="carihareketi_hareket_turu_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carihareketi",
            index=models.Index(
                fields=["cari", "tarih"], name="carihareketi_cari_tarih_idx"
            ),
        ),
    ]
