# Generated by Django 6.0 on 2025-12-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0005_remove_vade_tarihi"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cari",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cari_account",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı Hesabı",
            ),
        ),
    ]
