# Generated by Django 4.2.7 on 2025-12-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stok", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "db_table": "stok_kategori",
                "ordering": ["ad"],
            },
        ),
        migrations.AlterField(
            model_name="urun",
            name="ad",
            field=models.CharField(max_length=200, verbose_name="Ürün Adı"),
        ),
        migrations.AlterField(
            model_name="urun",
            name="barkod",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Barkod",
            ),
        ),
        migrations.AlterField(
            model_name="urun",
            name="fiyat",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Birim Fiyatı"
            ),
        ),
        migrations.AlterField(
            model_name="urun",
            name="stok_adedi",
            field=models.IntegerField(default=0, verbose_name="Stok Miktarı"),
        ),
        migrations.CreateModel(
            name="StokHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hareket_tipi",
                    models.CharField(
                        choices=[("IN", "Stok Girişi"), ("OUT", "Stok Çıkışı")],
                        max_length=3,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                ("miktar", models.IntegerField(verbose_name="Miktar")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stok.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
                "db_table": "stok_stokhareketi",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddField(
            model_name="urun",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stok.kategori",
                verbose_name="Kategori",
            ),
        ),
    ]
