# Generated by Django 6.0 on 2025-12-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0003_update_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stokhareketi",
            options={
                "ordering": ["-tarih"],
                "verbose_name": "Stok Hareketi",
                "verbose_name_plural": "Stok Hareketleri",
            },
        ),
        migrations.AlterField(
            model_name="stokhareketi",
            name="islem_turu",
            field=models.CharField(
                choices=[("giriş", "Giriş"), ("çıkış", "Çıkış")],
                max_length=10,
                verbose_name="İşlem Türü",
            ),
        ),
        migrations.AlterField(
            model_name="stokhareketi",
            name="olusturan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="İşlemi Yapan Kullanıcı",
            ),
        ),
    ]
