# Generated by Django 4.2.7 on 2025-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0004_alter_stokhareketi_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="alis_fiyati",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Alış Fiyatı"
            ),
        ),
        migrations.AddField(
            model_name="urun",
            name="kdv_orani",
            field=models.DecimalField(
                decimal_places=2, default=20, max_digits=5, verbose_name="KDV Oranı (%)"
            ),
        ),
        migrations.AddField(
            model_name="urun",
            name="uretici_firma",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Üretici Firma"
            ),
        ),
    ]
