# Generated by Django 4.2.7 on 2025-12-08 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0005_urun_alis_fiyati_urun_kdv_orani_urun_uretici_firma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="urun",
            name="alis_fiyati",
        ),
        migrations.RemoveField(
            model_name="urun",
            name="kdv_orani",
        ),
        migrations.RemoveField(
            model_name="urun",
            name="uretici_firma",
        ),
    ]
