# Generated by Django 6.0 on 2025-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0006_remove_urun_alis_fiyati_remove_urun_kdv_orani_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="urun",
            name="min_stok_adedi",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Minimum Stok Seviyesi"
            ),
        ),
    ]
