# Generated by Django 6.0 on 2025-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0008_set_min_stok_to_zero"),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="qr_kod",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_kodlar/", verbose_name="QR Kod"
            ),
        ),
        migrations.AddField(
            model_name="urun",
            name="resim",
            field=models.ImageField(
                blank=True, null=True, upload_to="urunler/", verbose_name="Ürün Resmi"
            ),
        ),
    ]
