# Generated by Django 6.0 on 2025-12-10 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stok", "0009_urun_qr_kod_urun_resim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="urun",
            name="alis_fiyati",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Alış Fiyatı (₺)",
            ),
        ),
        migrations.AlterField(
            model_name="urun",
            name="fiyat",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Satış Fiyatı (₺)"
            ),
        ),
        migrations.AddIndex(
            model_name="stokhareketi",
            index=models.Index(fields=["tarih"], name="stokhareketi_tarih_idx"),
        ),
        migrations.AddIndex(
            model_name="stokhareketi",
            index=models.Index(
                fields=["islem_turu"], name="stokhareketi_islem_turu_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stokhareketi",
            index=models.Index(
                fields=["urun", "tarih"], name="stokhareketi_urun_tarih_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="urun",
            index=models.Index(fields=["ad"], name="urun_ad_idx"),
        ),
    ]
