# Generated by Django 6.0 on 2025-12-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cari", "0006_cari_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanelDuyurusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200, verbose_name="Başlık")),
                ("icerik", models.TextField(verbose_name="İçerik")),
                (
                    "yayin_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayın Tarihi"
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                (
                    "onemli",
                    models.BooleanField(default=False, verbose_name="Önemli mi?"),
                ),
            ],
            options={
                "verbose_name": "Panel Duyurusu",
                "verbose_name_plural": "Panel Duyuruları",
                "ordering": ["-yayin_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="MusteriTalebi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Talep Başlığı"),
                ),
                ("mesaj", models.TextField(verbose_name="Mesaj")),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("acik", "Açık"),
                            ("islemde", "İşlemde"),
                            ("tamamlandi", "Tamamlandı"),
                            ("iptal", "İptal Edildi"),
                        ],
                        default="acik",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "yanit",
                    models.TextField(
                        blank=True, null=True, verbose_name="Firma Yanıtı"
                    ),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talepler",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Talebi",
                "verbose_name_plural": "Müşteri Talepleri",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
    ]
