# Generated by Django 6.0 on 2025-12-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0006_cari_user"),
        ("musteri_paneli", "0001_initial"),
        ("stok", "0009_urun_qr_kod_urun_resim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Siparis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "siparis_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Sipariş No"
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Onay Bekliyor"),
                            ("onaylandi", "Onaylandı"),
                            ("reddedildi", "Reddedildi"),
                            ("faturalandi", "Faturalandı"),
                            ("iptal", "İptal Edildi"),
                        ],
                        default="beklemede",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notlar",
                    models.TextField(
                        blank=True, null=True, verbose_name="Müşteri Notu"
                    ),
                ),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Toplam Tutar",
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "cari",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siparisler",
                        to="cari.cari",
                        verbose_name="Cari",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş",
                "verbose_name_plural": "Siparişler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="SiparisKalem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "miktar",
                    models.PositiveIntegerField(default=1, verbose_name="Miktar"),
                ),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "siparis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalemler",
                        to="musteri_paneli.siparis",
                        verbose_name="Sipariş",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stok.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş Kalemi",
                "verbose_name_plural": "Sipariş Kalemleri",
            },
        ),
        migrations.DeleteModel(
            name="MusteriTalebi",
        ),
    ]
