# Generated by Django 4.2.7 on 2025-12-08 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
                ("adres", models.TextField(blank=True, null=True)),
                ("pozisyon", models.CharField(blank=True, max_length=100, null=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_userprofile",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Oluşturma"),
                            ("update", "Güncelleme"),
                            ("delete", "Silme"),
                            ("view", "Görüntüleme"),
                            ("export", "Dışa Aktarma"),
                            ("login", "Giriş"),
                            ("logout", "Çıkış"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("model_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_auditlog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="accounts_au_timesta_40aa9a_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="accounts_au_user_id_1110c4_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="accounts_au_action_918219_idx",
                    ),
                ],
            },
        ),
    ]
