# Generated by Django 6.0 on 2025-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="guncelleme_tarihi",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
