# Generated by Django 6.0 on 2025-12-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_guncelleme_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Oluşturma"),
                    ("update", "Güncelleme"),
                    ("delete", "Silme"),
                    ("view", "Görüntüleme"),
                    ("login", "Giriş"),
                    ("logout", "Çıkış"),
                ],
                max_length=20,
            ),
        ),
    ]
