# Generated by Django 4.2.7 on 2025-12-07 14:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HesapKart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200, verbose_name="Hesap Adı")),
                (
                    "hesap_tipi",
                    models.CharField(
                        choices=[
                            ("banka", "Banka"),
                            ("kasa", "Kasa"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Hesap Tipi",
                    ),
                ),
                (
                    "hesap_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Hesap No"
                    ),
                ),
                (
                    "bakiye",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Bakiye (₺)",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("durum", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesap Kartı",
                "verbose_name_plural": "Hesap Kartları",
                "db_table": "finans_hesapkart",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="FinansHareketi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hareket_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Hareket No"
                    ),
                ),
                (
                    "hareket_tipi",
                    models.CharField(
                        choices=[
                            ("gelir", "Gelir"),
                            ("gider", "Gider"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                        verbose_name="Hareket Tipi",
                    ),
                ),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Açıklama")),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Belge No"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "hedef_hesap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_hareketleri",
                        to="finans.hesapkart",
                        verbose_name="Hedef Hesap",
                    ),
                ),
                (
                    "hesap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hareketler",
                        to="finans.hesapkart",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finans Hareketi",
                "verbose_name_plural": "Finans Hareketleri",
                "db_table": "finans_finanshareketi",
                "ordering": ["-tarih", "-id"],
            },
        ),
    ]
