# Generated by Django 6.0 on 2025-12-16 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fis_no",
                    models.CharField(
                        help_text="Sistem tarafından otomatik üretilebilir.",
                        max_length=50,
                        unique=True,
                        verbose_name="Fiş No",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "source_invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Kaynak Fatura No",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Fişi",
                "verbose_name_plural": "Muhasebe Fişleri",
                "db_table": "finans_journalentry",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Hesap Kodu")),
                ("name", models.CharField(max_length=255, verbose_name="Hesap Adı")),
                (
                    "type",
                    models.CharField(
                        help_text="Örn: Varlık, Borç, Gelir, Gider",
                        max_length=50,
                        verbose_name="Hesap Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Hesabı",
                "verbose_name_plural": "Muhasebe Hesapları",
                "db_table": "finans_account",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["code"], name="account_code_idx")],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Borç"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Alacak",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finans.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finans.journalentry",
                        verbose_name="Fiş",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muhasebe Fiş Satırı",
                "verbose_name_plural": "Muhasebe Fiş Satırları",
                "db_table": "finans_journalline",
            },
        ),
    ]
