# Generated by Django 6.0 on 2025-12-24 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finans", "0002_journalentry_account_journalline"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="account",
            name="account_code_idx",
        ),
        migrations.RemoveField(
            model_name="journalline",
            name="account",
        ),
        migrations.RemoveField(
            model_name="journalline",
            name="entry",
        ),
        migrations.DeleteModel(
            name="Account",
        ),
        migrations.DeleteModel(
            name="JournalEntry",
        ),
        migrations.DeleteModel(
            name="JournalLine",
        ),
    ]
