# Generated by Django 4.2.7 on 2025-12-07 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasrafKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Masraf Kategorisi",
                "verbose_name_plural": "Masraf Kategorileri",
                "db_table": "masraf_masrafkategori",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Masraf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "masraf_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Masraf No"
                    ),
                ),
                ("aciklama", models.TextField(verbose_name="Açıklama")),
                (
                    "tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Tutar (₺)"
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "odeme_yontemi",
                    models.CharField(
                        choices=[
                            ("nakit", "Nakit"),
                            ("havale", "Havale"),
                            ("kredi_karti", "Kredi Kartı"),
                            ("cek", "Çek"),
                        ],
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("odendi", "Ödendi"),
                            ("beklemede", "Beklemede"),
                            ("iptal", "İptal"),
                        ],
                        default="beklemede",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "belge_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Belge No"
                    ),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="masraf.masrafkategori",
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Masraf",
                "verbose_name_plural": "Masraflar",
                "db_table": "masraf_masraf",
                "ordering": ["-tarih", "-id"],
            },
        ),
    ]
