# Generated by Django 6.0 on 2025-12-24 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("masraf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masraf",
            name="kategori",
        ),
        migrations.DeleteModel(
            name="MasrafKategori",
        ),
    ]
