# Generated by Django 4.2.7 on 2025-12-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stok", "0001_initial"),
        ("cari", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fatura_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Fatura No"
                    ),
                ),
                ("fatura_tarihi", models.DateField(verbose_name="Fatura Tarihi")),
                (
                    "vade_tarihi",
                    models.DateField(blank=True, null=True, verbose_name="Vade Tarihi"),
                ),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Toplam Tutar",
                    ),
                ),
                (
                    "kdv_tutari",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="KDV Tutarı",
                    ),
                ),
                (
                    "genel_toplam",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Genel Toplam",
                    ),
                ),
                (
                    "fatura_tipi",
                    models.CharField(
                        choices=[("Satis", "Satış"), ("Alis", "Alış")],
                        default="Satis",
                        max_length=20,
                        verbose_name="Fatura Tipi",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("Beklemede", "Beklemede"),
                            ("Odendi", "Ödendi"),
                            ("Iptal", "İptal"),
                        ],
                        default="Beklemede",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "aciklama",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "olusturma_tarihi",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturma Tarihi"
                    ),
                ),
                (
                    "guncelleme_tarihi",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncelleme Tarihi"
                    ),
                ),
                (
                    "musteri",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cari.musteri",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "db_table": "fatura_fatura",
                "ordering": ["-fatura_tarihi", "-olusturma_tarihi"],
            },
        ),
        migrations.CreateModel(
            name="FaturaKalem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urun_adi", models.CharField(max_length=100, verbose_name="Ürün Adı")),
                ("miktar", models.IntegerField(default=1, verbose_name="Miktar")),
                (
                    "birim_fiyat",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "kdv_orani",
                    models.IntegerField(default=20, verbose_name="KDV Oranı (%)"),
                ),
                (
                    "kdv_tutari",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="KDV Tutarı",
                    ),
                ),
                (
                    "toplam_tutar",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                ("sira_no", models.IntegerField(default=1, verbose_name="Sıra No")),
                (
                    "fatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalemler",
                        to="fatura.fatura",
                        verbose_name="Fatura",
                    ),
                ),
                (
                    "urun",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stok.urun",
                        verbose_name="Ürün",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Kalemi",
                "verbose_name_plural": "Fatura Kalemleri",
                "db_table": "fatura_faturakalem",
                "ordering": ["sira_no"],
            },
        ),
    ]
