# Generated by Django 4.2.7 on 2025-12-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0002_cari_carihareketi_carinotu"),
        ("fatura", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatura",
            name="musteri",
        ),
        migrations.AddField(
            model_name="fatura",
            name="cari",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cari.cari",
                verbose_name="Cari",
            ),
        ),
    ]
