# Generated by Django 4.2.7 on 2025-12-07 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fatura", "0002_remove_fatura_musteri_fatura_cari"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="olusturan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Oluşturan",
            ),
        ),
    ]
