# Generated by Django 6.0 on 2025-12-08 21:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fatura", "0003_fatura_olusturan"),
    ]

    operations = [
        migrations.AddField(
            model_name="fatura",
            name="iskonto_orani",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                verbose_name="İskonto Oranı (%)",
            ),
        ),
        migrations.AddField(
            model_name="fatura",
            name="iskonto_tutari",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="İskonto Tutarı",
            ),
        ),
    ]
