# Generated by Django 6.0 on 2025-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fatura", "0004_fatura_iskonto_orani_fatura_iskonto_tutari"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="fatura_no",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Fatura No",
            ),
        ),
    ]
