# Generated by Django 6.0 on 2025-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fatura", "0005_alter_fatura_fatura_no"),
    ]

    operations = [
        migrations.RunSQL(
            # PostgreSQL için: Eski constraint'i sil ve yeni SET NULL constraint'i oluştur
            sql=[
                # Eski constraint'i sil
                "ALTER TABLE fatura_faturakalem DROP CONSTRAINT IF EXISTS fatura_faturakalemi_urun_id_fk;",
                # Yeni constraint'i SET NULL ile oluştur
                "ALTER TABLE fatura_faturakalem ADD CONSTRAINT fatura_faturakalemi_urun_id_fk "
                "FOREIGN KEY (urun_id) REFERENCES stok_urun(id) ON DELETE SET NULL;",
            ],
            reverse_sql=[
                # Geri alma: Eski constraint'i geri yükle (CASCADE olarak)
                "ALTER TABLE fatura_faturakalem DROP CONSTRAINT IF EXISTS fatura_faturakalemi_urun_id_fk;",
                "ALTER TABLE fatura_faturakalem ADD CONSTRAINT fatura_faturakalemi_urun_id_fk "
                "FOREIGN KEY (urun_id) REFERENCES stok_urun(id) ON DELETE CASCADE;",
            ],
        ),
    ]
