# Generated by Django 6.0 on 2025-12-10 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fatura", "0006_fix_faturakalem_urun_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fatura",
            name="vade_tarihi",
        ),
    ]
