# Generated by Django 6.0 on 2025-12-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fatura", "0007_remove_vade_tarihi"),
    ]

    operations = [
        migrations.RunSQL(
            # PostgreSQL için: FaturaKalem'in fatura foreign key constraint'ini CASCADE olarak ayarla
            sql=[
                # Eski constraint'i sil
                "ALTER TABLE fatura_faturakalem DROP CONSTRAINT IF EXISTS fatura_faturakalemi_fatura_id_fk;",
                # Yeni constraint'i CASCADE ile oluştur
                "ALTER TABLE fatura_faturakalem ADD CONSTRAINT fatura_faturakalemi_fatura_id_fk "
                "FOREIGN KEY (fatura_id) REFERENCES fatura_fatura(id) ON DELETE CASCADE;",
            ],
            reverse_sql=[
                # Geri alma
                "ALTER TABLE fatura_faturakalem DROP CONSTRAINT IF EXISTS fatura_faturakalemi_fatura_id_fk;",
                "ALTER TABLE fatura_faturakalem ADD CONSTRAINT fatura_faturakalemi_fatura_id_fk "
                "FOREIGN KEY (fatura_id) REFERENCES fatura_fatura(id) ON DELETE RESTRICT;",
            ],
        ),
    ]
