# Generated by Django 6.0 on 2025-12-10 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cari", "0005_remove_vade_tarihi"),
        ("fatura", "0008_fix_faturakalem_cascade_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="durum",
            field=models.CharField(
                choices=[
                    ("AcikHesap", "Açık Hesap"),
                    ("KasadanKapanacak", "Kasadan Kapanacak"),
                ],
                default="AcikHesap",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddIndex(
            model_name="fatura",
            index=models.Index(fields=["fatura_tarihi"], name="fatura_tarihi_idx"),
        ),
        migrations.AddIndex(
            model_name="fatura",
            index=models.Index(fields=["fatura_tipi"], name="fatura_tipi_idx"),
        ),
        migrations.AddIndex(
            model_name="fatura",
            index=models.Index(fields=["durum"], name="fatura_durum_idx"),
        ),
        migrations.AddIndex(
            model_name="fatura",
            index=models.Index(
                fields=["cari", "fatura_tarihi"], name="fatura_cari_tarih_idx"
            ),
        ),
    ]
